///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'RS_Pasien'
// Generated by LLBLGen v1.21.2003.712 Final on: Tuesday, October 16, 2007, 9:40:32 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace SIMRS.DataAccess
{
	/// <summary>
	/// Purpose: Data Access class for the table 'RS_Pasien'.
	/// </summary>
	public class RS_Pasien : DBInteractionBase
	{
		#region Class Member Declarations
			private SqlInt64		_pasienId;
			private SqlDateTime		_createdDate, _tanggalLahir, _modifiedDate;
			private SqlInt32		_statusPerkawinanId, _statusPerkawinanIdOld, _kabupatenKotaId, _kabupatenKotaIdOld, _propinsiId, _propinsiIdOld, _createdBy, _modifiedBy, _agamaId, _agamaIdOld, _pendidikanId, _pendidikanIdOld, _kecamatanId, _kecamatanIdOld, _statusId, _statusIdOld, _pangkatId, _pangkatIdOld, _kelurahanDesaId, _kelurahanDesaIdOld;
        private SqlString _noAskes, _noKTP, _golDarah, _teleponKantor, _alamatKantor, _keterangan, _noRM, _nama, _jenisKelamin, _telepon, _alamat, _tempatLahir, _pekerjaan, _nRP, _jabatan, _kesatuan, _alamatKesatuan;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public RS_Pasien()
		{
			// Nothing for now.
		}

        public bool IsExist()
        {
            SqlCommand cmdToExecute = new SqlCommand();
            cmdToExecute.CommandText = "dbo.[RS_Pasien_IsExist]";
            cmdToExecute.CommandType = CommandType.StoredProcedure;

            // Use base class' connection object
            cmdToExecute.Connection = _mainConnection;

            try
            {
                cmdToExecute.Parameters.Add(new SqlParameter("@PasienId", SqlDbType.BigInt, 8, ParameterDirection.Input, false, 19, 0, "", DataRowVersion.Proposed, _pasienId));
                cmdToExecute.Parameters.Add(new SqlParameter("@NoRM", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _noRM));
                cmdToExecute.Parameters.Add(new SqlParameter("@IsExist", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));
                cmdToExecute.Parameters.Add(new SqlParameter("@ErrorMessage", SqlDbType.VarChar, 255, ParameterDirection.Output, false, 0, 0, "", DataRowVersion.Proposed, _errorMessage));
                cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

                // Open connection.
                _mainConnection.Open();

                // Execute query.
                _rowsAffected = cmdToExecute.ExecuteNonQuery();
                int IsExist = int.Parse(cmdToExecute.Parameters["@IsExist"].Value.ToString());
                _errorMessage = (SqlString)cmdToExecute.Parameters["@ErrorMessage"].Value;
                _errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;
                
                if (_errorCode != (int)LLBLError.AllOk)
                {
                    // Throw error.
                    throw new Exception("Stored Procedure 'RS_Pasien_IsExist' reported the ErrorCode: " + _errorCode);
                }

                return IsExist == 1;
            }
            catch (Exception ex)
            {
                // some error occured. Bubble it to caller and encapsulate Exception object
                throw new Exception("RS_Pasien::IsExist::Error occured.", ex);
            }
            finally
            {
                // Close connection.
                _mainConnection.Close();
                cmdToExecute.Dispose();
            }
        }

        public bool IsExistRM()
        {
            SqlCommand cmdToExecute = new SqlCommand();
            cmdToExecute.CommandText = "dbo.[RS_Pasien_IsExistRM]";
            cmdToExecute.CommandType = CommandType.StoredProcedure;

            // Use base class' connection object
            cmdToExecute.Connection = _mainConnection;

            try
            {
                cmdToExecute.Parameters.Add(new SqlParameter("@NoRM", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _noRM));
                cmdToExecute.Parameters.Add(new SqlParameter("@IsExist", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));
                cmdToExecute.Parameters.Add(new SqlParameter("@ErrorMessage", SqlDbType.VarChar, 255, ParameterDirection.Output, false, 0, 0, "", DataRowVersion.Proposed, _errorMessage));
                cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

                // Open connection.
                _mainConnection.Open();

                // Execute query.
                _rowsAffected = cmdToExecute.ExecuteNonQuery();
                int IsExist = int.Parse(cmdToExecute.Parameters["@IsExist"].Value.ToString());
                _errorMessage = (SqlString)cmdToExecute.Parameters["@ErrorMessage"].Value;
                _errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

                if (_errorCode != (int)LLBLError.AllOk)
                {
                    // Throw error.
                    throw new Exception("Stored Procedure 'RS_Pasien_IsExistRM' reported the ErrorCode: " + _errorCode);
                }

                return IsExist == 1;
            }
            catch (Exception ex)
            {
                // some error occured. Bubble it to caller and encapsulate Exception object
                throw new Exception("RS_Pasien::IsExistRM::Error occured.", ex);
            }
            finally
            {
                // Close connection.
                _mainConnection.Close();
                cmdToExecute.Dispose();
            }
        }

        /// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PasienId</LI>
		///		 <LI>NoRM</LI>
		///		 <LI>Nama</LI>
		///		 <LI>StatusId. May be SqlInt32.Null</LI>
		///		 <LI>PangkatId. May be SqlInt32.Null</LI>
        ///		 <LI>NoAskes. May be SqlString.Null</LI>
        ///		 <LI>NoKTP. May be SqlString.Null</LI>
        ///		 <LI>GolDarah. May be SqlString.Null</LI>
        ///		 <LI>NRP. May be SqlString.Null</LI>
        ///		 <LI>Jabatan. May be SqlString.Null</LI>
        ///		 <LI>Kesatuan. May be SqlString.Null</LI>
        ///		 <LI>AlamatKesatuan. May be SqlString.Null</LI>
		///		 <LI>TempatLahir. May be SqlString.Null</LI>
		///		 <LI>TanggalLahir. May be SqlDateTime.Null</LI>
		///		 <LI>Alamat. May be SqlString.Null</LI>
		///		 <LI>KelurahanDesaId. May be SqlInt32.Null</LI>
		///		 <LI>KecamatanId. May be SqlInt32.Null</LI>
		///		 <LI>KabupatenKotaId. May be SqlInt32.Null</LI>
		///		 <LI>PropinsiId. May be SqlInt32.Null</LI>
		///		 <LI>Telepon. May be SqlString.Null</LI>
		///		 <LI>JenisKelamin. May be SqlString.Null</LI>
		///		 <LI>StatusPerkawinanId. May be SqlInt32.Null</LI>
		///		 <LI>AgamaId. May be SqlInt32.Null</LI>
		///		 <LI>PendidikanId. May be SqlInt32.Null</LI>
		///		 <LI>Pekerjaan. May be SqlString.Null</LI>
		///		 <LI>AlamatKantor. May be SqlString.Null</LI>
		///		 <LI>TeleponKantor. May be SqlString.Null</LI>
		///		 <LI>Keterangan. May be SqlString.Null</LI>
		///		 <LI>CreatedBy</LI>
		///		 <LI>CreatedDate</LI>
		///		 <LI>ModifiedBy. May be SqlInt32.Null</LI>
		///		 <LI>ModifiedDate. May be SqlDateTime.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_Insert]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@NoRM", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _noRM));
				cmdToExecute.Parameters.Add(new SqlParameter("@Nama", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nama));
				cmdToExecute.Parameters.Add(new SqlParameter("@StatusId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _statusId));
				cmdToExecute.Parameters.Add(new SqlParameter("@PangkatId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _pangkatId));
                cmdToExecute.Parameters.Add(new SqlParameter("@NoAskes", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _noAskes));
                cmdToExecute.Parameters.Add(new SqlParameter("@NoKTP", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _noKTP));
                cmdToExecute.Parameters.Add(new SqlParameter("@GolDarah", SqlDbType.VarChar, 2, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _golDarah));
                cmdToExecute.Parameters.Add(new SqlParameter("@NRP", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _nRP));
				cmdToExecute.Parameters.Add(new SqlParameter("@Jabatan", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _jabatan));
                cmdToExecute.Parameters.Add(new SqlParameter("@Kesatuan", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _kesatuan));
                cmdToExecute.Parameters.Add(new SqlParameter("@AlamatKesatuan", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _alamatKesatuan));
                cmdToExecute.Parameters.Add(new SqlParameter("@TempatLahir", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _tempatLahir));
				cmdToExecute.Parameters.Add(new SqlParameter("@TanggalLahir", SqlDbType.DateTime, 8, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _tanggalLahir));
				cmdToExecute.Parameters.Add(new SqlParameter("@Alamat", SqlDbType.VarChar, 250, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _alamat));
				cmdToExecute.Parameters.Add(new SqlParameter("@KelurahanDesaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kelurahanDesaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@KecamatanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kecamatanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@KabupatenKotaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kabupatenKotaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@PropinsiId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _propinsiId));
				cmdToExecute.Parameters.Add(new SqlParameter("@Telepon", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _telepon));
				cmdToExecute.Parameters.Add(new SqlParameter("@JenisKelamin", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _jenisKelamin));
				cmdToExecute.Parameters.Add(new SqlParameter("@StatusPerkawinanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _statusPerkawinanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@AgamaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _agamaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@PendidikanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _pendidikanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@Pekerjaan", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _pekerjaan));
				cmdToExecute.Parameters.Add(new SqlParameter("@AlamatKantor", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _alamatKantor));
				cmdToExecute.Parameters.Add(new SqlParameter("@TeleponKantor", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _teleponKantor));
				cmdToExecute.Parameters.Add(new SqlParameter("@Keterangan", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _keterangan));
				cmdToExecute.Parameters.Add(new SqlParameter("@CreatedBy", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _createdBy));
				cmdToExecute.Parameters.Add(new SqlParameter("@CreatedDate", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _createdDate));
				cmdToExecute.Parameters.Add(new SqlParameter("@ModifiedBy", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _modifiedBy));
				cmdToExecute.Parameters.Add(new SqlParameter("@ModifiedDate", SqlDbType.DateTime, 8, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _modifiedDate));
                cmdToExecute.Parameters.Add(new SqlParameter("@PasienId", SqlDbType.BigInt, 8, ParameterDirection.Output, true, 19, 0, "", DataRowVersion.Proposed, _pasienId));
                cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
                _pasienId = (SqlInt64)cmdToExecute.Parameters["@PasienId"].Value;
                _errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_Insert' reported the ErrorCode: " + _errorCode);
				}

				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::Insert::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PasienId</LI>
		///		 <LI>NoRM</LI>
		///		 <LI>Nama</LI>
		///		 <LI>StatusId. May be SqlInt32.Null</LI>
		///		 <LI>PangkatId. May be SqlInt32.Null</LI>
        ///		 <LI>NoAskes. May be SqlString.Null</LI>
        ///		 <LI>NoKTP. May be SqlString.Null</LI>
        ///		 <LI>GolDarah. May be SqlString.Null</LI>
        ///		 <LI>NRP. May be SqlString.Null</LI>
        ///		 <LI>Jabatan. May be SqlString.Null</LI>
        ///		 <LI>Kesatuan. May be SqlString.Null</LI>
        ///		 <LI>AlamatKesatuan. May be SqlString.Null</LI>
        ///		 <LI>TempatLahir. May be SqlString.Null</LI>
		///		 <LI>TanggalLahir. May be SqlDateTime.Null</LI>
		///		 <LI>Alamat. May be SqlString.Null</LI>
		///		 <LI>KelurahanDesaId. May be SqlInt32.Null</LI>
		///		 <LI>KecamatanId. May be SqlInt32.Null</LI>
		///		 <LI>KabupatenKotaId. May be SqlInt32.Null</LI>
		///		 <LI>PropinsiId. May be SqlInt32.Null</LI>
		///		 <LI>Telepon. May be SqlString.Null</LI>
		///		 <LI>JenisKelamin. May be SqlString.Null</LI>
		///		 <LI>StatusPerkawinanId. May be SqlInt32.Null</LI>
		///		 <LI>AgamaId. May be SqlInt32.Null</LI>
		///		 <LI>PendidikanId. May be SqlInt32.Null</LI>
		///		 <LI>Pekerjaan. May be SqlString.Null</LI>
		///		 <LI>AlamatKantor. May be SqlString.Null</LI>
		///		 <LI>TeleponKantor. May be SqlString.Null</LI>
		///		 <LI>Keterangan. May be SqlString.Null</LI>
		///		 <LI>CreatedBy</LI>
		///		 <LI>CreatedDate</LI>
		///		 <LI>ModifiedBy. May be SqlInt32.Null</LI>
		///		 <LI>ModifiedDate. May be SqlDateTime.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_Update]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@PasienId", SqlDbType.BigInt, 8, ParameterDirection.Input, false, 19, 0, "", DataRowVersion.Proposed, _pasienId));
				cmdToExecute.Parameters.Add(new SqlParameter("@NoRM", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _noRM));
				cmdToExecute.Parameters.Add(new SqlParameter("@Nama", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nama));
				cmdToExecute.Parameters.Add(new SqlParameter("@StatusId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _statusId));
				cmdToExecute.Parameters.Add(new SqlParameter("@PangkatId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _pangkatId));
                cmdToExecute.Parameters.Add(new SqlParameter("@NoAskes", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _noAskes));
                cmdToExecute.Parameters.Add(new SqlParameter("@NoKTP", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _noKTP));
                cmdToExecute.Parameters.Add(new SqlParameter("@GolDarah", SqlDbType.VarChar, 2, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _golDarah));
                cmdToExecute.Parameters.Add(new SqlParameter("@NRP", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _nRP));
                cmdToExecute.Parameters.Add(new SqlParameter("@Jabatan", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _jabatan));
                cmdToExecute.Parameters.Add(new SqlParameter("@Kesatuan", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _kesatuan));
                cmdToExecute.Parameters.Add(new SqlParameter("@AlamatKesatuan", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _alamatKesatuan));
                cmdToExecute.Parameters.Add(new SqlParameter("@TempatLahir", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _tempatLahir));
				cmdToExecute.Parameters.Add(new SqlParameter("@TanggalLahir", SqlDbType.DateTime, 8, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _tanggalLahir));
				cmdToExecute.Parameters.Add(new SqlParameter("@Alamat", SqlDbType.VarChar, 250, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _alamat));
				cmdToExecute.Parameters.Add(new SqlParameter("@KelurahanDesaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kelurahanDesaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@KecamatanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kecamatanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@KabupatenKotaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kabupatenKotaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@PropinsiId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _propinsiId));
				cmdToExecute.Parameters.Add(new SqlParameter("@Telepon", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _telepon));
				cmdToExecute.Parameters.Add(new SqlParameter("@JenisKelamin", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _jenisKelamin));
				cmdToExecute.Parameters.Add(new SqlParameter("@StatusPerkawinanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _statusPerkawinanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@AgamaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _agamaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@PendidikanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _pendidikanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@Pekerjaan", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _pekerjaan));
				cmdToExecute.Parameters.Add(new SqlParameter("@AlamatKantor", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _alamatKantor));
				cmdToExecute.Parameters.Add(new SqlParameter("@TeleponKantor", SqlDbType.VarChar, 50, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _teleponKantor));
				cmdToExecute.Parameters.Add(new SqlParameter("@Keterangan", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _keterangan));
				cmdToExecute.Parameters.Add(new SqlParameter("@CreatedBy", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _createdBy));
				cmdToExecute.Parameters.Add(new SqlParameter("@CreatedDate", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _createdDate));
				cmdToExecute.Parameters.Add(new SqlParameter("@ModifiedBy", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _modifiedBy));
				cmdToExecute.Parameters.Add(new SqlParameter("@ModifiedDate", SqlDbType.DateTime, 8, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, _modifiedDate));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_Update' reported the ErrorCode: " + _errorCode);
				}

				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::Update::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PasienId</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_Delete]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@PasienId", SqlDbType.BigInt, 8, ParameterDirection.Input, false, 19, 0, "", DataRowVersion.Proposed, _pasienId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_Delete' reported the ErrorCode: " + _errorCode);
				}

				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::Delete::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method. This method will Select one existing row from the database, based on the Primary Key.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PasienId</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		///		 <LI>PasienId</LI>
		///		 <LI>NoRM</LI>
		///		 <LI>Nama</LI>
		///		 <LI>StatusId</LI>
		///		 <LI>PangkatId</LI>
		///		 <LI>NRP</LI>
		///		 <LI>Kesatuan</LI>
		///		 <LI>TempatLahir</LI>
		///		 <LI>TanggalLahir</LI>
		///		 <LI>Alamat</LI>
		///		 <LI>KelurahanDesaId</LI>
		///		 <LI>KecamatanId</LI>
		///		 <LI>KabupatenKotaId</LI>
		///		 <LI>PropinsiId</LI>
		///		 <LI>Telepon</LI>
		///		 <LI>JenisKelamin</LI>
		///		 <LI>StatusPerkawinanId</LI>
		///		 <LI>AgamaId</LI>
		///		 <LI>PendidikanId</LI>
		///		 <LI>Pekerjaan</LI>
		///		 <LI>AlamatKantor</LI>
		///		 <LI>TeleponKantor</LI>
		///		 <LI>Keterangan</LI>
		///		 <LI>CreatedBy</LI>
		///		 <LI>CreatedDate</LI>
		///		 <LI>ModifiedBy</LI>
		///		 <LI>ModifiedDate</LI>
		/// </UL>
		/// Will fill all properties corresponding with a field in the table with the value of the row selected.
		/// </remarks>
		public override DataTable SelectOne()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectOne]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@PasienId", SqlDbType.BigInt, 8, ParameterDirection.Input, false, 19, 0, "", DataRowVersion.Proposed, _pasienId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectOne' reported the ErrorCode: " + _errorCode);
				}

				if(toReturn.Rows.Count > 0)
				{
					_pasienId = (Int64)toReturn.Rows[0]["PasienId"];
					_noRM = (string)toReturn.Rows[0]["NoRM"];
					_nama = (string)toReturn.Rows[0]["Nama"];
					_statusId = toReturn.Rows[0]["StatusId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["StatusId"];
					_pangkatId = toReturn.Rows[0]["PangkatId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["PangkatId"];
                    _noAskes = toReturn.Rows[0]["NoAskes"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["NoAskes"];
                    _noKTP = toReturn.Rows[0]["NoKTP"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["NoKTP"];
                    _golDarah = toReturn.Rows[0]["GolDarah"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["GolDarah"];
                    _nRP = toReturn.Rows[0]["NRP"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["NRP"];
                    _jabatan = toReturn.Rows[0]["Jabatan"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["Jabatan"];
                    _kesatuan = toReturn.Rows[0]["Kesatuan"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["Kesatuan"];
                    _alamatKesatuan = toReturn.Rows[0]["AlamatKesatuan"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["AlamatKesatuan"];
                    _tempatLahir = toReturn.Rows[0]["TempatLahir"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["TempatLahir"];
					_tanggalLahir = toReturn.Rows[0]["TanggalLahir"] == System.DBNull.Value ? SqlDateTime.Null : (DateTime)toReturn.Rows[0]["TanggalLahir"];
					_alamat = toReturn.Rows[0]["Alamat"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["Alamat"];
					_kelurahanDesaId = toReturn.Rows[0]["KelurahanDesaId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["KelurahanDesaId"];
					_kecamatanId = toReturn.Rows[0]["KecamatanId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["KecamatanId"];
					_kabupatenKotaId = toReturn.Rows[0]["KabupatenKotaId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["KabupatenKotaId"];
					_propinsiId = toReturn.Rows[0]["PropinsiId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["PropinsiId"];
					_telepon = toReturn.Rows[0]["Telepon"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["Telepon"];
					_jenisKelamin = toReturn.Rows[0]["JenisKelamin"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["JenisKelamin"];
					_statusPerkawinanId = toReturn.Rows[0]["StatusPerkawinanId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["StatusPerkawinanId"];
					_agamaId = toReturn.Rows[0]["AgamaId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["AgamaId"];
					_pendidikanId = toReturn.Rows[0]["PendidikanId"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["PendidikanId"];
					_pekerjaan = toReturn.Rows[0]["Pekerjaan"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["Pekerjaan"];
					_alamatKantor = toReturn.Rows[0]["AlamatKantor"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["AlamatKantor"];
					_teleponKantor = toReturn.Rows[0]["TeleponKantor"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["TeleponKantor"];
					_keterangan = toReturn.Rows[0]["Keterangan"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["Keterangan"];
					_createdBy = (Int32)toReturn.Rows[0]["CreatedBy"];
					_createdDate = (DateTime)toReturn.Rows[0]["CreatedDate"];
					_modifiedBy = toReturn.Rows[0]["ModifiedBy"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["ModifiedBy"];
					_modifiedDate = toReturn.Rows[0]["ModifiedDate"] == System.DBNull.Value ? SqlDateTime.Null : (DateTime)toReturn.Rows[0]["ModifiedDate"];
				}
				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectOne::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: SelectAll method. This method will Select all rows from the table.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public override DataTable SelectAll()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAll]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAll' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAll::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'StatusId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>StatusId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWStatusIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWStatusIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@StatusId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _statusId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWStatusIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWStatusIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'PangkatId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PangkatId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWPangkatIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWPangkatIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@PangkatId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _pangkatId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWPangkatIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWPangkatIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'KelurahanDesaId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>KelurahanDesaId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWKelurahanDesaIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWKelurahanDesaIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@KelurahanDesaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kelurahanDesaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWKelurahanDesaIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWKelurahanDesaIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'KecamatanId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>KecamatanId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWKecamatanIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWKecamatanIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@KecamatanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kecamatanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWKecamatanIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWKecamatanIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'KabupatenKotaId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>KabupatenKotaId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWKabupatenKotaIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWKabupatenKotaIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@KabupatenKotaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _kabupatenKotaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWKabupatenKotaIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWKabupatenKotaIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'PropinsiId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PropinsiId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWPropinsiIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWPropinsiIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@PropinsiId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _propinsiId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWPropinsiIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWPropinsiIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'StatusPerkawinanId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>StatusPerkawinanId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWStatusPerkawinanIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWStatusPerkawinanIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@StatusPerkawinanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _statusPerkawinanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWStatusPerkawinanIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWStatusPerkawinanIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'AgamaId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>AgamaId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWAgamaIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWAgamaIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@AgamaId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _agamaId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWAgamaIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWAgamaIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method for a foreign key. This method will Select one or more rows from the database, based on the Foreign Key 'PendidikanId'
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>PendidikanId. May be SqlInt32.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ErrorCode</LI>
		/// </UL>
		/// </remarks>
		public DataTable SelectAllWPendidikanIdLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllWPendidikanIdLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("RS_Pasien");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@PendidikanId", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, _pendidikanId));
				cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				// Open connection.
				_mainConnection.Open();

				// Execute query.
				adapter.Fill(toReturn);
				_errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

				if(_errorCode != (int)LLBLError.AllOk)
				{
					// Throw error.
					throw new Exception("Stored Procedure 'RS_Pasien_SelectAllWPendidikanIdLogic' reported the ErrorCode: " + _errorCode);
				}

				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("RS_Pasien::SelectAllWPendidikanIdLogic::Error occured.", ex);
			}
			finally
			{
				// Close connection.
				_mainConnection.Close();
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}

        public DataTable SelectAllFilter()
        {
            SqlCommand cmdToExecute = new SqlCommand();
            cmdToExecute.CommandText = "dbo.[RS_Pasien_SelectAllFilter]";
            cmdToExecute.CommandType = CommandType.StoredProcedure;
            DataTable toReturn = new DataTable("RS_Pasien");
            SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

            // Use base class' connection object
            cmdToExecute.Connection = _mainConnection;

            try
            {
                cmdToExecute.Parameters.Add(new SqlParameter("@NoRM", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _noRM));
                cmdToExecute.Parameters.Add(new SqlParameter("@Nama", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nama));
                cmdToExecute.Parameters.Add(new SqlParameter("@NRP", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nRP));
                cmdToExecute.Parameters.Add(new SqlParameter("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, true, 10, 0, "", DataRowVersion.Proposed, _errorCode));

                // Open connection.
                _mainConnection.Open();

                // Execute query.
                adapter.Fill(toReturn);
                _errorCode = (SqlInt32)cmdToExecute.Parameters["@ErrorCode"].Value;

                if (_errorCode != (int)LLBLError.AllOk)
                {
                    // Throw error.
                    throw new Exception("Stored Procedure 'RS_Pasien_SelectAllFilter' reported the ErrorCode: " + _errorCode);
                }

                return toReturn;
            }
            catch (Exception ex)
            {
                // some error occured. Bubble it to caller and encapsulate Exception object
                throw new Exception("RS_Pasien::SelectAllFilter::Error occured.", ex);
            }
            finally
            {
                // Close connection.
                _mainConnection.Close();
                cmdToExecute.Dispose();
                adapter.Dispose();
            }
        }

		#region Class Property Declarations
		public SqlInt64 PasienId
		{
			get
			{
				return _pasienId;
			}
			set
			{
				SqlInt64 pasienIdTmp = (SqlInt64)value;
				if(pasienIdTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("PasienId", "PasienId can't be NULL");
				}
				_pasienId = value;
			}
		}


		public SqlString NoRM
		{
			get
			{
				return _noRM;
			}
			set
			{
				SqlString noRMTmp = (SqlString)value;
				if(noRMTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NoRM", "NoRM can't be NULL");
				}
				_noRM = value;
			}
		}


		public SqlString Nama
		{
			get
			{
				return _nama;
			}
			set
			{
				SqlString namaTmp = (SqlString)value;
				if(namaTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("Nama", "Nama can't be NULL");
				}
				_nama = value;
			}
		}


		public SqlInt32 StatusId
		{
			get
			{
				return _statusId;
			}
			set
			{
				_statusId = value;
			}
		}
		public SqlInt32 StatusIdOld
		{
			get
			{
				return _statusIdOld;
			}
			set
			{
				_statusIdOld = value;
			}
		}


		public SqlInt32 PangkatId
		{
			get
			{
				return _pangkatId;
			}
			set
			{
				_pangkatId = value;
			}
		}
		public SqlInt32 PangkatIdOld
		{
			get
			{
				return _pangkatIdOld;
			}
			set
			{
				_pangkatIdOld = value;
			}
		}

        public SqlString NoAskes
        {
            get
            {
                return _noAskes;
            }
            set
            {
                _noAskes = value;
            }
        }
        public SqlString NoKTP
        {
            get
            {
                return _noKTP;
            }
            set
            {
                _noKTP = value;
            }
        }
        public SqlString GolDarah
        {
            get
            {
                return _golDarah;
            }
            set
            {
                _golDarah = value;
            }
        }

		public SqlString NRP
		{
			get
			{
				return _nRP;
			}
			set
			{
				_nRP = value;
			}
		}


        public SqlString Jabatan
        {
            get
            {
                return _jabatan;
            }
            set
            {
                _jabatan = value;
            }
        }
        public SqlString Kesatuan
        {
            get
            {
                return _kesatuan;
            }
            set
            {
                _kesatuan = value;
            }
        }
        public SqlString AlamatKesatuan
        {
            get
            {
                return _alamatKesatuan;
            }
            set
            {
                _alamatKesatuan = value;
            }
        }


		public SqlString TempatLahir
		{
			get
			{
				return _tempatLahir;
			}
			set
			{
				_tempatLahir = value;
			}
		}


		public SqlDateTime TanggalLahir
		{
			get
			{
				return _tanggalLahir;
			}
			set
			{
				_tanggalLahir = value;
			}
		}


		public SqlString Alamat
		{
			get
			{
				return _alamat;
			}
			set
			{
				_alamat = value;
			}
		}


		public SqlInt32 KelurahanDesaId
		{
			get
			{
				return _kelurahanDesaId;
			}
			set
			{
				_kelurahanDesaId = value;
			}
		}
		public SqlInt32 KelurahanDesaIdOld
		{
			get
			{
				return _kelurahanDesaIdOld;
			}
			set
			{
				_kelurahanDesaIdOld = value;
			}
		}


		public SqlInt32 KecamatanId
		{
			get
			{
				return _kecamatanId;
			}
			set
			{
				_kecamatanId = value;
			}
		}
		public SqlInt32 KecamatanIdOld
		{
			get
			{
				return _kecamatanIdOld;
			}
			set
			{
				_kecamatanIdOld = value;
			}
		}


		public SqlInt32 KabupatenKotaId
		{
			get
			{
				return _kabupatenKotaId;
			}
			set
			{
				_kabupatenKotaId = value;
			}
		}
		public SqlInt32 KabupatenKotaIdOld
		{
			get
			{
				return _kabupatenKotaIdOld;
			}
			set
			{
				_kabupatenKotaIdOld = value;
			}
		}


		public SqlInt32 PropinsiId
		{
			get
			{
				return _propinsiId;
			}
			set
			{
				_propinsiId = value;
			}
		}
		public SqlInt32 PropinsiIdOld
		{
			get
			{
				return _propinsiIdOld;
			}
			set
			{
				_propinsiIdOld = value;
			}
		}


		public SqlString Telepon
		{
			get
			{
				return _telepon;
			}
			set
			{
				_telepon = value;
			}
		}


		public SqlString JenisKelamin
		{
			get
			{
				return _jenisKelamin;
			}
			set
			{
				_jenisKelamin = value;
			}
		}


		public SqlInt32 StatusPerkawinanId
		{
			get
			{
				return _statusPerkawinanId;
			}
			set
			{
				_statusPerkawinanId = value;
			}
		}
		public SqlInt32 StatusPerkawinanIdOld
		{
			get
			{
				return _statusPerkawinanIdOld;
			}
			set
			{
				_statusPerkawinanIdOld = value;
			}
		}


		public SqlInt32 AgamaId
		{
			get
			{
				return _agamaId;
			}
			set
			{
				_agamaId = value;
			}
		}
		public SqlInt32 AgamaIdOld
		{
			get
			{
				return _agamaIdOld;
			}
			set
			{
				_agamaIdOld = value;
			}
		}


		public SqlInt32 PendidikanId
		{
			get
			{
				return _pendidikanId;
			}
			set
			{
				_pendidikanId = value;
			}
		}
		public SqlInt32 PendidikanIdOld
		{
			get
			{
				return _pendidikanIdOld;
			}
			set
			{
				_pendidikanIdOld = value;
			}
		}


		public SqlString Pekerjaan
		{
			get
			{
				return _pekerjaan;
			}
			set
			{
				_pekerjaan = value;
			}
		}


		public SqlString AlamatKantor
		{
			get
			{
				return _alamatKantor;
			}
			set
			{
				_alamatKantor = value;
			}
		}


		public SqlString TeleponKantor
		{
			get
			{
				return _teleponKantor;
			}
			set
			{
				_teleponKantor = value;
			}
		}


		public SqlString Keterangan
		{
			get
			{
				return _keterangan;
			}
			set
			{
				_keterangan = value;
			}
		}


		public SqlInt32 CreatedBy
		{
			get
			{
				return _createdBy;
			}
			set
			{
				SqlInt32 createdByTmp = (SqlInt32)value;
				if(createdByTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("CreatedBy", "CreatedBy can't be NULL");
				}
				_createdBy = value;
			}
		}


		public SqlDateTime CreatedDate
		{
			get
			{
				return _createdDate;
			}
			set
			{
				SqlDateTime createdDateTmp = (SqlDateTime)value;
				if(createdDateTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("CreatedDate", "CreatedDate can't be NULL");
				}
				_createdDate = value;
			}
		}


		public SqlInt32 ModifiedBy
		{
			get
			{
				return _modifiedBy;
			}
			set
			{
				_modifiedBy = value;
			}
		}


		public SqlDateTime ModifiedDate
		{
			get
			{
				return _modifiedDate;
			}
			set
			{
				_modifiedDate = value;
			}
		}
		#endregion
	}
}
